AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  xgboost-api

  SAM Template for xgboost-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180

Resources:
  GetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: xgboost_api/
      Handler: get.lambda_handler
      Runtime: python3.7
      Policies: 
        - AmazonSageMakerFullAccess
      Events:
        Get:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /xgboost-api
            Method: get


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for GET function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/xgboost-api/"

  GetFunction:
    Description: "GET Lambda Function ARN"
    Value: !GetAtt GetFunction.Arn

  GetFunctionIamRole:
    Description: "Implicit IAM Role created for GET function"
    Value: !GetAtt GetFunctionRole.Arn

